BC/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fmq.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
     url(r'^$', 'BC.views.index',name='index'),
     url(r'^search/$', 'BC.views.search', name='search'),
     url(r'^profile/(?P<username>\w+)/$', 'BC.views.profile', name='profile'),
     url(r'^logs/$', 'BC.views.circles', name='circles'),
     url(r'^logs/group/create$', 'BC.views.circle_create', name='circle_create'),
     url(r'^logs/(?P<id>\d+)$', 'BC.views.logs', name='logs'),
     url(r'^logs/(?P<id>\d+)/add/$', 'BC.views.new_log', name='add_log'),
     url(r'^logs/(?P<pid>\d+)/detail/(?P<id>\d+)/$', 'BC.views.log_detail', name='log_detail'),
     url(r'^logs/(?P<pid>\d+)/detail/(?P<id>\d+)/add/$', 'BC.views.log_detail_add', name='log_detail_add'),
   )

logit/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('main.urls', namespace="main")), #allowed routes for login, logout, register
    url('', include('BC.urls', namespace="businesscore")),
    url('', include('social.apps.django_app.urls', namespace="social"))
    #url(r'^dashboard/', include('main.urls')), #maps mysite.com/dashboard to everything that is coded in main app
]

main/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fmq.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^login/$', 'main.views.login', name='login'), #maps url to login 
    url(r'^password/reset/$', 'main.views.pass_reset', name='pass_reset'),
    url(r'^signup/$', 'main.views.signup', name='signup'),
    url(r'^logout/$', 'main.views.logout_view', name='logout'),
   )

BC/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Logs

from datetime import datetime  

# Create your models here.
class Notification(models.Model):
	created = models.DateTimeField(editable=False, auto_now_add=True)
	content = models.TextField(verbose_name='Notification')
	owner = models.ForeignKey(User, related_name='owner')
	from_notification = models.ForeignKey(User, related_name='creator')

BC/forms.py
from django.contrib.auth.models import User
from main.models import *
from django import forms

class CircleForm(forms.ModelForm):

	class Meta:
		model = Circles
		fields = ('name', 'description', 'group')

	def __init__(self, *args, **kwargs):
		super(CircleForm, self).__init__(*args, **kwargs)
		self.fields['group'].widget = forms.CheckboxSelectMultiple()

class TinyLogForm(forms.ModelForm):
	class Meta:
		model = tinylog
		fields = ('value', 'who')

class LogForm(forms.ModelForm):
	class Meta:
		model = Logs
		fields = ('description',)

BC/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from django.db.models import Sum
from main.models import *
from BC.models import *

from BC.forms import *
# Create your views here.

#function that will get notifications from any user
def notify(logged_user):
	return Notification.objects.filter(owner=logged_user)
	
@login_required
def index(request):
	notifications = notify(request.user) #get notifications

	return HttpResponseRedirect('/logs/')

@login_required
def search(request):
	notifications = notify(request.user)
	if 'q' in request.GET: #if a search has been done
		template = 'BC/search.html'
		result = []
		query = request.GET['q'].strip() #remove whitespace on the begining or the end of the string
		if (' ' in request.GET['q']) == True: #if there is a space in the string e.g. 'chino y nacho' will return True
			first_name = query.partition(' ')[0] #gets 'chino' from string
			last_name = query.split(' ',1)[1:][0]#gets 'y nacho' from string

			#assuming that the name exists, will proceed doing the search 
			#First, we'll check if the exact name exists. If True, then we have found our user! CASE INSENSITIVE
			complete_user = User.objects.filter(first_name__iexact=first_name, last_name__iexact=last_name)
			if complete_user:
				result.extend(list(complete_user))
				instance = RequestContext(request, locals())
				return render_to_response(template, context_instance=instance)
			#Else, we'll find any coincidences with them names. CASE INSENSITIVE
			complete_user = User.objects.filter(first_name__icontains=first_name, last_name__icontains=last_name)
			first_name_filter = User.objects.filter(first_name__icontains=first_name)
			last_name_filter = User.objects.filter(last_name__icontains=last_name)

			result.extend(list(complete_user))
			result.extend(list(first_name_filter))
			result.extend(list(last_name_filter))
			
			result = set(result)

			instance = RequestContext(request, locals())
			return render_to_response(template, context_instance=instance)
		
		#Username could be unique. So let's check if the exact string exists. If True, we have found our user! CASE INSENSITIVE
		username_filter = User.objects.filter(username__iexact=request.GET['q'])
		if username_filter:
			result.extend(list(username_filter))
			instance = RequestContext(request, locals())
			return render_to_response(template, context_instance=instance)

		#Else, we'll find any match CASE INSENSITIVE
		username_filter = User.objects.filter(username__icontains=request.GET['q'])

		#Now we find any coincidence with the fist_name or last_name param CASE INSENSITIVE
		first_name_filter = User.objects.filter(first_name__icontains=request.GET['q'])
		last_name_filter = User.objects.filter(last_name__icontains=request.GET['q'])
		
		result.extend(list(username_filter))
		result.extend(list(first_name_filter))
		result.extend(list(last_name_filter))

		result = set(result)

		instance = RequestContext(request, locals())
		return render_to_response(template, context_instance=instance)
	return HttpResponseRedirect('/')

@login_required
def profile(request, username):
	notifications = notify(request.user)
	#first, check if user exists. Else, redirect to 'search'
	try:
		user_friend = User.objects.get(username=username)
	except User.DoesNotExist:
		return HttpResponseRedirect('/search?q='+username)


	#Now, we got the request.user and the user_friend. We'll try and check if the User_friend added the request.user as a friend
	friend_request = Friendship.objects.filter(creator=user_friend,friend=request.user)
	if friend_request:
		friend_request = friend_request[0]
		#Ok! There's a friendship, now let's check if the status is Pending
		if friend_request.status == 'P':
			#Set a flag true! To render the buttons of "Accept" or "Decline"
			friend_request_flag = True
		
	#now, we check if there's a friendship. If there is, then we load the user profile, if not, the option to add friend will be available
	friendship = Friendship.objects.filter(creator=request.user,friend=user_friend)
	if friendship:
		friendship = friendship[0]

	#if theres and 'add' then we should add a new friend
	if 'add' in request.GET:
		if request.GET['add'] == 'true':
			if not user_friend == request.user:
				#If there is a existing Friend Request, we update the status
				try:
					friend_request = Friendship.objects.get(creator=user_friend,friend=request.user)
					#So it means that we have a status = N. Let's update it to 'P'
					friend_request.friend_request_sent()
				except Friendship.DoesNotExist:					
					#else, create record for friendship. Here, we have a status of pending.
					f1_request = Friendship(creator=request.user, friend=user_friend, status='P')
					f1_request.save()
					#we must now create a notification to the user_friend, so he can accept the friend request
					content = 'Hi there! Please add me as your friend! - ' + request.user.username
					notification = Notification(owner=user_friend, from_notification=request.user,content=content)
					notification.save()
			return HttpResponseRedirect('/profile/'+username)

	#let's unfriend!
	if 'unfriend' in request.GET:
		if not user_friend == request.user:
			#let's make sure the status is 'A' so we can unfriend
			if friend_request.status == 'A':
				#now we unfriend
				friend_request.delete()
				friendship.delete()
		return HttpResponseRedirect('/profile/'+username)

	#If there is a Accept or Decline in a friendship
	if 'accept' in request.GET or 'decline' in request.GET:
		#Let's make sure that there is, in fact, a friend request to accept or decline
		if friend_request:
			#Now let's make sure that the status is Pending
			if friend_request_flag:
				f = Notification.objects.filter(owner=request.user, from_notification=user_friend)
				
				#now, we'll handle the decline. IF decline, we'll just update the status to N
				if 'decline' in request.GET:
					friend_request.unfriend()
					#If there is the other way friendship, we need to set to 'N' its status. If not, then do nothing else
					if friendship:
						friendship.unfriend()
					if f:
						f = f[0]
						f.delete()
				#IF accept, we'll update friend_request to 'A' AND add the other way relationship so now user X is friend of Y AND user Y is friend of X
				elif 'accept' in request.GET:
					friend_request.friend_request_accepted()
					if f:
						f = f[0]
						f.delete()
					#add new friendship
					new_friendship = Friendship(creator=request.user,friend=user_friend,status='A')
					new_friendship.save()
				return HttpResponseRedirect('/profile/'+username)

	template = 'BC/profile.html'
	instance = RequestContext(request, locals())
	return render_to_response(template, context_instance=instance)

@login_required
def circles(request):
	notifications = notify(request.user)
	my_circles = []
	# we must know search all circles from a request.user
	my_friendships = Friendship.objects.filter(creator=request.user)
	if my_friendships:
		#for friendship in my_friendships:
		my_circles.extend(list(Circles.objects.filter(group=my_friendships).order_by('-pk')))

	#perhaps, he didn't create the group?
	my_friendships = Friendship.objects.filter(friend=request.user)
	if my_friendships:
		#for friendship in my_friendships:
		my_circles.extend(list(Circles.objects.filter(group=my_friendships).order_by('-pk')))

	print my_circles
	my_circles = set(my_circles)

	#return HttpResponse(my_circles)

	template = 'BC/circles.html'
	instance = RequestContext(request, locals())
	return render_to_response(template, context_instance=instance)

@login_required
def circle_create(request):
	notifications = notify(request.user)
	#get all friends of the request.user
	friends = Friendship.objects.filter(creator=request.user, status='A')

	if 'save' in request.POST:
		values = request.POST.getlist('group')
		new_circle = Circles(name=request.POST['name'], description=request.POST['description'])
		new_circle.save()
		print new_circle.pk
		for item in values:
			i = Friendship.objects.filter(pk=item)
			if i:
				new_circle.group.add(i[0])
		
		return HttpResponseRedirect('/logs/')
		

	template = 'BC/circle_add.html'
	instance = RequestContext(request, locals())
	return render_to_response(template, context_instance=instance)
	#TODO - puedes agregar, pero no puedes modificar ni buscar

@login_required
def logs(request, id):
	notifications = notify(request.user)
	log_list = Logs.objects.filter(group=id).order_by('description') #list of log for the current group. ESTE ES MI OBJETO PRINCIPAL
	friendships = Circles.objects.filter(pk=id) #current group information. needed to access friends in the group.
	current_id = id;
	d = {} #values for log 
	a = [] #to build the next url. We'll save here the pk of each logs
	b = []
	counter = 0
	if friendships: 
		friendships = friendships[0]
		users = util(friendships)
		for obj in log_list:
			l = {} #values for users
			items = tinylog.objects.filter(log=obj)
			a.append(items[0].pk)
			print log_list[counter].description
			b.append(log_list[counter].description)
			counter += 1
			for user in users:
				aux = items.filter(who=user)
				l[user] = aux.aggregate(Sum('value'))['value__sum']
			l['total'] = items.aggregate(Sum('value'))['value__sum']
			d[obj.description] = l

	
	template = 'BC/logs.html'
	instance = RequestContext(request, locals())
	return render_to_response(template, context_instance=instance)

@login_required
def log_detail(request, pid, id):
	notifications = notify(request.user)
	curr1 = pid
	curr2 = id
	log_list = Logs.objects.filter(pk=id)	
	if log_list:
		log_list = log_list[0]
	tinylog_list = tinylog.objects.filter(log=log_list)

	template='BC/history_detail_log.html'
	instance = RequestContext(request, locals())
	return render_to_response(template, context_instance=instance)

BC/templates/BC/newlog.html
<!DOCTYPE html>
{% load humanize %}
<html lang="en" class="no-js">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8">
<title>LogIT! | Admin Dashboard</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta content="" name="description">
<meta content="" name="author">
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css">
<link href="/static/BC/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="/static/BC/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css">
<link href="/static/BC/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/static/BC/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
<link href="/static/BC/global/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css">
<link href="/static/BC/global/plugins/morris/morris.css" rel="stylesheet" type="text/css">
<!-- END PAGE LEVEL PLUGIN STYLES -->
<!-- BEGIN PAGE STYLES -->
<link href="/static/BC/admin/pages/css/tasks.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE STYLES -->
<!-- BEGIN THEME STYLES -->
<!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
<link href="/static/BC/global/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css">
<link href="/static/BC/global/css/plugins.css" rel="stylesheet" type="text/css">
<link href="/static/BC/admin/layout3/css/layout.css" rel="stylesheet" type="text/css">
<link href="/static/BC/admin/layout3/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color">
<link href="/static/BC/admin/layout3/css/custom.css" rel="stylesheet" type="text/css">
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico">
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<!-- DOC: Apply "page-header-menu-fixed" class to set the mega menu fixed  -->
<!-- DOC: Apply "page-header-top-fixed" class to set the top menu fixed  -->
<body>
<div class="page-header">
	<!-- BEGIN HEADER TOP -->
	<div class="page-header-top">
		<div class="container">
			
			<!-- BEGIN RESPONSIVE MENU TOGGLER -->
			<a href="javascript:;" class="menu-toggler"></a>
			<!-- END RESPONSIVE MENU TOGGLER -->
			<!-- BEGIN TOP NAVIGATION MENU -->
			<div class="top-menu">
				<ul class="nav navbar-nav pull-right">
					<!-- BEGIN NOTIFICATION DROPDOWN -->
					<li class="dropdown dropdown-extended dropdown-dark dropdown-notification" id="header_notification_bar">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<i class="icon-bell"></i>
						{% if notifications.count > 0 %}
						<span class="badge badge-default">{{ notifications.count }}</span>
						{% endif %}
						</a>
						<ul class="dropdown-menu">
							<li class="external">
								<h3>You have <strong>{{ notifications.count }} pending{{ notifications.count|pluralize }}</strong> notification{{ notifications.count|pluralize }}</h3>
							</li>
							{% if notifications.count > 0 %}
							<li>
								<ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
								{% for notification in notifications %}
									<li>
										<a href="/profile/{{notification.from_notification.username}}?friendrequest=true">
										<span class="time">{{notification.created|naturaltime}}</span>
										<span class="details">
										<span class="label label-sm label-icon label-success">
										<i class="fa fa-plus"></i>
										</span>
										New friend request </span>
										</a>
									</li>
								{% endfor %}
								</ul>
							</li>
							{% endif %}
						</ul>
					</li>
					<!-- END NOTIFICATION DROPDOWN -->
					
					<li class="droddown dropdown-separator">
						<span class="separator"></span>
					</li>
					
					<!-- BEGIN USER LOGIN DROPDOWN -->
					<li class="dropdown dropdown-user dropdown-dark">
						<a href="/profile/{{request.user}}" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<img alt="" class="img-circle" src="/static/BC/admin/layout3/img/avatar9.jpg">
						<span class="username username-hide-mobile">{{ user.get_full_name|default:user.username }}</span>
						</a>
						<ul class="dropdown-menu dropdown-menu-default">
							<li>
								<a href="/profile/{{request.user}}">
								<i class="icon-user"></i> My Profile </a>
							</li>
							<li class="divider">
							</li>
							<li>
								<a href="{% url 'main:logout' %}">
								<i class="icon-key"></i> Log Out </a>
							</li>
						</ul>
					</li>
					<!-- END USER LOGIN DROPDOWN -->
					<!-- BEGIN USER LOGIN DROPDOWN -->
					
					<!-- END USER LOGIN DROPDOWN -->
				</ul>
			</div>
			<!-- END TOP NAVIGATION MENU -->
		</div>
	</div>
	<!-- END HEADER TOP -->
	<!-- BEGIN HEADER MENU -->
	<div class="page-header-menu">
		<div class="container">
			<!-- BEGIN HEADER SEARCH BOX -->
			<form class="search-form" action="{% url 'businesscore:search' %}" method="GET">
				<div class="input-group">
					<input type="text" class="form-control" style="color:#CED0DE;" placeholder="Search Users" name="q">
					<span class="input-group-btn">
					<a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
					</span>
				</div>
			</form>
			<!-- END HEADER SEARCH BOX -->
			<!-- BEGIN MEGA MENU -->
			<!-- DOC: Apply "hor-menu-light" class after the "hor-menu" class below to have a horizontal menu with white background -->
			<!-- DOC: Remove data-hover="dropdown" and data-close-others="true" attributes below to disable the dropdown opening on mouse hover -->
			<div class="hor-menu ">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="/" >
						Logs</i>
						</a>
					</li>
					<li class="menu-dropdown classic-menu-dropdown ">
						<a href="/search/?q=">
						Search</i>
						</a>
					</li>
				</ul>
			</div>
			<!-- END MEGA MENU -->
		</div>
	</div>
	<!-- END HEADER MENU -->
</div>
<!-- END HEADER -->
<!-- BEGIN PAGE CONTAINER -->
<div class="page-container">
	<!-- BEGIN PAGE HEAD -->
	<div class="page-head">
		<div class="container">
			<!-- BEGIN PAGE TITLE -->
			<div class="page-title">
				<h1>Logs view <small>view logs list</small></h1>
			</div>
			<!-- END PAGE TITLE -->		</div>
	</div>
	<!-- END PAGE HEAD -->
	<!-- BEGIN PAGE CONTENT -->
	<div class="page-content">
		<div class="container">
			<!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							<h4 class="modal-title">Modal title</h4>
						</div>
						<div class="modal-body">
							 Widget settings form goes here
						</div>
						<div class="modal-footer">
							<button type="button" class="btn blue">Save changes</button>
							<button type="button" class="btn default" data-dismiss="modal">Close</button>
						</div>
					</div>
					<!-- /.modal-content -->
				</div>
				<!-- /.modal-dialog -->
			</div>
			<!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
			<!-- BEGIN PAGE BREADCRUMB -->
			<ul class="page-breadcrumb breadcrumb">
				<li>
					<a href="/">Log Group</a><i class="fa fa-circle"></i>
				</li>
				<li>
					<a href="/logs/{{curent_id}}">Logs</a>
					<i class="fa fa-circle"></i>
				</li>
				<li class="active">
					 Add Log
				</li>
			</ul>
			<!-- END PAGE BREADCRUMB -->
			<!-- BEGIN PAGE CONTENT INNER -->
			<div class="row">
				<div class="col-md-12">
					<!-- Begin: life time stats -->
					<div class="portlet light">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-gift font-green-sharp"></i>
								<span class="caption-subject font-green-sharp bold uppercase">Add Log</span>
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-container">
								<table class="table table-striped table-bordered table-hover" id="datatable_products">
								<thead>
								<tr role="row" class="heading">
									<th width="60%">
										 Description
									</th>
									<th width="20%">
										 User
									</th>
									<th width="20%">
										 Amount
									</th>
									<th>
									Actions
									</th>
								</tr>
								<tr role="row" class="filter">
								<form action="" method="POST">
								{% csrf_token %}
								{{ logform.non_field_errors }}
									<td>
										<input type="text" class="form-control" name="description" value="{{logform.description.value|default_if_none:''}}" required>
										{{logform.description.errors}}
									</td>
									<td>
										{{tinylogform.who.value|default_if_none:request.user.get_full_name|default:request.user.username}}
										<input type="hidden" name="who" value="{{tinylogform.who.value|default:request.user.username}}" />
									</td>
									<td>
										<input type="number" class="form-control form-filter input-sm" step="0.01" name="value" value="{{tinylogform.value.value|default_if_none:''}}" required>
										{{tinylogform.value.errors}}
									</td>
									
									<td>
										<div class="margin-bottom-5">
											<button type="submit" class="btn btn-sm blue filter-submit margin-bottom" name="save"><i class="fa fa-check"></i> Save</button>
										</div>
										<a href="/logs/{{current_id}}" class="btn btn-sm red filter-cancel"><i class="fa fa-times"></i> Cancel</a>
									</td>
								</form>
								</tr>
								</thead>
								<tbody>
								</tbody>
								</table>
							</div>
						</div>
					</div>
					<!-- End: life time stats -->
				</div>
			</div>
			<!-- END PAGE CONTENT INNER -->
		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER -->

<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="container">
		 2015 &copy; LogIT!
	</div>
</div>
<div class="scroll-to-top">
	<i class="icon-arrow-up"></i>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/static/BC/global/plugins/respond.min.js"></script>
<script src="/static/BC/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<script src="/static/BC/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/static/BC/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="/static/BC/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="/static/BC/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/static/BC/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/static/BC/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/static/BC/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/static/BC/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="/static/BC/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script type="text/javascript" src="/static/BC/global/plugins/select2/select2.min.js"></script>
<script type="text/javascript" src="/static/BC/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/static/BC/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
<script type="text/javascript" src="/static/BC/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/static/BC/global/scripts/metronic.js" type="text/javascript"></script>
<script src="/static/BC/admin/layout3/scripts/layout.js" type="text/javascript"></script>
<script src="/static/BC/admin/layout3/scripts/demo.js" type="text/javascript"></script>
<script src="/static/BC/global/scripts/datatable.js"></script>
<script src="/static/BC/admin/pages/scripts/ecommerce-products.js"></script>

<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>